# Generated by Django 6.0.7 on 2026-08-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registrationsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registrationsession',
            name='role',
            field=models.CharField(choices=[('trainee', 'Trainee'), ('trainer', 'Trainer'), ('company', 'Company'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email', 'purpose', 'is_used'], name='accounts_ot_email_74c3d9_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_57ad4f_idx'),
        ),
    ]
