# Generated by Django 6.0.7 on 2026-08-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_updated_at_registrationsession_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationsession',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('trainee', 'Trainee'), ('trainer', 'Trainer'), ('company', 'Company'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
