/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SmartHubRouteImport } from './routes/smart-hub'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MentorshipProgramRouteImport } from './routes/mentorship-program'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AiFeaturesRouteImport } from './routes/ai-features'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorshipProgramIndexRouteImport } from './routes/mentorship-program/index'
import { Route as TrainerDashboardRouteImport } from './routes/trainer.dashboard'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as MentorshipProgramCompanyIdRouteImport } from './routes/mentorship-program/$companyId'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as MentorshipProgramGoogleMehulSampathRouteImport } from './routes/mentorship-program/google/mehul-sampath'
import { Route as MentorshipProgramAmazonSouravAggarwalRouteImport } from './routes/mentorship-program/amazon/sourav-aggarwal'
import { Route as MentorshipProgramAmazonPurvabhSuranaRouteImport } from './routes/mentorship-program/amazon/purvabh-surana'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SmartHubRoute = SmartHubRouteImport.update({
  id: '/smart-hub',
  path: '/smart-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipProgramRoute = MentorshipProgramRouteImport.update({
  id: '/mentorship-program',
  path: '/mentorship-program',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AiFeaturesRoute = AiFeaturesRouteImport.update({
  id: '/ai-features',
  path: '/ai-features',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipProgramIndexRoute = MentorshipProgramIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorshipProgramRoute,
} as any)
const TrainerDashboardRoute = TrainerDashboardRouteImport.update({
  id: '/trainer/dashboard',
  path: '/trainer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipProgramCompanyIdRoute =
  MentorshipProgramCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => MentorshipProgramRoute,
  } as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipProgramGoogleMehulSampathRoute =
  MentorshipProgramGoogleMehulSampathRouteImport.update({
    id: '/google/mehul-sampath',
    path: '/google/mehul-sampath',
    getParentRoute: () => MentorshipProgramRoute,
  } as any)
const MentorshipProgramAmazonSouravAggarwalRoute =
  MentorshipProgramAmazonSouravAggarwalRouteImport.update({
    id: '/amazon/sourav-aggarwal',
    path: '/amazon/sourav-aggarwal',
    getParentRoute: () => MentorshipProgramRoute,
  } as any)
const MentorshipProgramAmazonPurvabhSuranaRoute =
  MentorshipProgramAmazonPurvabhSuranaRouteImport.update({
    id: '/amazon/purvabh-surana',
    path: '/amazon/purvabh-surana',
    getParentRoute: () => MentorshipProgramRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-features': typeof AiFeaturesRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/mentorship-program': typeof MentorshipProgramRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-hub': typeof SmartHubRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/mentorship-program/$companyId': typeof MentorshipProgramCompanyIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/mentorship-program/': typeof MentorshipProgramIndexRoute
  '/mentorship-program/amazon/purvabh-surana': typeof MentorshipProgramAmazonPurvabhSuranaRoute
  '/mentorship-program/amazon/sourav-aggarwal': typeof MentorshipProgramAmazonSouravAggarwalRoute
  '/mentorship-program/google/mehul-sampath': typeof MentorshipProgramGoogleMehulSampathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-features': typeof AiFeaturesRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-hub': typeof SmartHubRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/mentorship-program/$companyId': typeof MentorshipProgramCompanyIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/mentorship-program': typeof MentorshipProgramIndexRoute
  '/mentorship-program/amazon/purvabh-surana': typeof MentorshipProgramAmazonPurvabhSuranaRoute
  '/mentorship-program/amazon/sourav-aggarwal': typeof MentorshipProgramAmazonSouravAggarwalRoute
  '/mentorship-program/google/mehul-sampath': typeof MentorshipProgramGoogleMehulSampathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-features': typeof AiFeaturesRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/companies': typeof CompaniesRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/mentors': typeof MentorsRoute
  '/mentorship-program': typeof MentorshipProgramRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/smart-hub': typeof SmartHubRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/mentorship-program/$companyId': typeof MentorshipProgramCompanyIdRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/trainer/dashboard': typeof TrainerDashboardRoute
  '/mentorship-program/': typeof MentorshipProgramIndexRoute
  '/mentorship-program/amazon/purvabh-surana': typeof MentorshipProgramAmazonPurvabhSuranaRoute
  '/mentorship-program/amazon/sourav-aggarwal': typeof MentorshipProgramAmazonSouravAggarwalRoute
  '/mentorship-program/google/mehul-sampath': typeof MentorshipProgramGoogleMehulSampathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-features'
    | '/blog'
    | '/careers'
    | '/companies'
    | '/contact'
    | '/faq'
    | '/features'
    | '/login'
    | '/mentors'
    | '/mentorship-program'
    | '/pricing'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/smart-hub'
    | '/success-stories'
    | '/support'
    | '/terms'
    | '/unauthorized'
    | '/verify-email'
    | '/admin/dashboard'
    | '/mentorship-program/$companyId'
    | '/student/dashboard'
    | '/trainer/dashboard'
    | '/mentorship-program/'
    | '/mentorship-program/amazon/purvabh-surana'
    | '/mentorship-program/amazon/sourav-aggarwal'
    | '/mentorship-program/google/mehul-sampath'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-features'
    | '/blog'
    | '/careers'
    | '/companies'
    | '/contact'
    | '/faq'
    | '/features'
    | '/login'
    | '/mentors'
    | '/pricing'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/smart-hub'
    | '/success-stories'
    | '/support'
    | '/terms'
    | '/unauthorized'
    | '/verify-email'
    | '/admin/dashboard'
    | '/mentorship-program/$companyId'
    | '/student/dashboard'
    | '/trainer/dashboard'
    | '/mentorship-program'
    | '/mentorship-program/amazon/purvabh-surana'
    | '/mentorship-program/amazon/sourav-aggarwal'
    | '/mentorship-program/google/mehul-sampath'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-features'
    | '/blog'
    | '/careers'
    | '/companies'
    | '/contact'
    | '/faq'
    | '/features'
    | '/login'
    | '/mentors'
    | '/mentorship-program'
    | '/pricing'
    | '/privacy'
    | '/programs'
    | '/sitemap.xml'
    | '/smart-hub'
    | '/success-stories'
    | '/support'
    | '/terms'
    | '/unauthorized'
    | '/verify-email'
    | '/admin/dashboard'
    | '/mentorship-program/$companyId'
    | '/student/dashboard'
    | '/trainer/dashboard'
    | '/mentorship-program/'
    | '/mentorship-program/amazon/purvabh-surana'
    | '/mentorship-program/amazon/sourav-aggarwal'
    | '/mentorship-program/google/mehul-sampath'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiFeaturesRoute: typeof AiFeaturesRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  CompaniesRoute: typeof CompaniesRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  MentorsRoute: typeof MentorsRoute
  MentorshipProgramRoute: typeof MentorshipProgramRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SmartHubRoute: typeof SmartHubRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  TrainerDashboardRoute: typeof TrainerDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/smart-hub': {
      id: '/smart-hub'
      path: '/smart-hub'
      fullPath: '/smart-hub'
      preLoaderRoute: typeof SmartHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship-program': {
      id: '/mentorship-program'
      path: '/mentorship-program'
      fullPath: '/mentorship-program'
      preLoaderRoute: typeof MentorshipProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-features': {
      id: '/ai-features'
      path: '/ai-features'
      fullPath: '/ai-features'
      preLoaderRoute: typeof AiFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship-program/': {
      id: '/mentorship-program/'
      path: '/'
      fullPath: '/mentorship-program/'
      preLoaderRoute: typeof MentorshipProgramIndexRouteImport
      parentRoute: typeof MentorshipProgramRoute
    }
    '/trainer/dashboard': {
      id: '/trainer/dashboard'
      path: '/trainer/dashboard'
      fullPath: '/trainer/dashboard'
      preLoaderRoute: typeof TrainerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship-program/$companyId': {
      id: '/mentorship-program/$companyId'
      path: '/$companyId'
      fullPath: '/mentorship-program/$companyId'
      preLoaderRoute: typeof MentorshipProgramCompanyIdRouteImport
      parentRoute: typeof MentorshipProgramRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship-program/google/mehul-sampath': {
      id: '/mentorship-program/google/mehul-sampath'
      path: '/google/mehul-sampath'
      fullPath: '/mentorship-program/google/mehul-sampath'
      preLoaderRoute: typeof MentorshipProgramGoogleMehulSampathRouteImport
      parentRoute: typeof MentorshipProgramRoute
    }
    '/mentorship-program/amazon/sourav-aggarwal': {
      id: '/mentorship-program/amazon/sourav-aggarwal'
      path: '/amazon/sourav-aggarwal'
      fullPath: '/mentorship-program/amazon/sourav-aggarwal'
      preLoaderRoute: typeof MentorshipProgramAmazonSouravAggarwalRouteImport
      parentRoute: typeof MentorshipProgramRoute
    }
    '/mentorship-program/amazon/purvabh-surana': {
      id: '/mentorship-program/amazon/purvabh-surana'
      path: '/amazon/purvabh-surana'
      fullPath: '/mentorship-program/amazon/purvabh-surana'
      preLoaderRoute: typeof MentorshipProgramAmazonPurvabhSuranaRouteImport
      parentRoute: typeof MentorshipProgramRoute
    }
  }
}

interface MentorshipProgramRouteChildren {
  MentorshipProgramCompanyIdRoute: typeof MentorshipProgramCompanyIdRoute
  MentorshipProgramIndexRoute: typeof MentorshipProgramIndexRoute
  MentorshipProgramAmazonPurvabhSuranaRoute: typeof MentorshipProgramAmazonPurvabhSuranaRoute
  MentorshipProgramAmazonSouravAggarwalRoute: typeof MentorshipProgramAmazonSouravAggarwalRoute
  MentorshipProgramGoogleMehulSampathRoute: typeof MentorshipProgramGoogleMehulSampathRoute
}

const MentorshipProgramRouteChildren: MentorshipProgramRouteChildren = {
  MentorshipProgramCompanyIdRoute: MentorshipProgramCompanyIdRoute,
  MentorshipProgramIndexRoute: MentorshipProgramIndexRoute,
  MentorshipProgramAmazonPurvabhSuranaRoute:
    MentorshipProgramAmazonPurvabhSuranaRoute,
  MentorshipProgramAmazonSouravAggarwalRoute:
    MentorshipProgramAmazonSouravAggarwalRoute,
  MentorshipProgramGoogleMehulSampathRoute:
    MentorshipProgramGoogleMehulSampathRoute,
}

const MentorshipProgramRouteWithChildren =
  MentorshipProgramRoute._addFileChildren(MentorshipProgramRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiFeaturesRoute: AiFeaturesRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  CompaniesRoute: CompaniesRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  MentorsRoute: MentorsRoute,
  MentorshipProgramRoute: MentorshipProgramRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SmartHubRoute: SmartHubRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  TrainerDashboardRoute: TrainerDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
